## Exploration des données

### DataFrames de base

In [1]:
import sys
import os
sys.path.append(os.path.abspath(".."))

In [2]:
from src.data.load_data import load_catnat, load_communes, load_regions, load_waterways

df = load_catnat()
gdf_communes = load_communes()
gdf_regions = load_regions()
gdf_water = load_waterways()

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 259867 entries, 0 to 259866
Data columns (total 10 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   cod_nat_catnat  259867 non-null  str
 1   cod_commune     259867 non-null  str
 2   lib_commune     259867 non-null  str
 3   num_risque_jo   256647 non-null  float64
 4   lib_risque_jo   259867 non-null  str
 5   dat_deb         259867 non-null  str
 6   dat_fin         259867 non-null  str
 7   dat_pub_arrete  259867 non-null  str
 8   dat_pub_jo      259867 non-null  str
 9   dat_maj         259867 non-null  str
dtypes: float64(1), str(9)
memory usage: 19.8 MB

In [5]:
df.head()

,cod_nat_catnat,cod_commune,lib_commune,num_risque_jo,lib_risque_jo,dat_deb,dat_fin,dat_pub_arrete,dat_pub_jo,dat_maj
0,BUDD8750027A,06120,Saint-Étienne-de-Tinée,63.0,Glissement de Terrain,1985-01-01,1986-12-31,1987-05-20,1987-05-24,2022-05-20
1,BUDD8750038A,2B050,Calvi,54.0,Inondations et/ou Coulées de Boue,1987-01-14,1987-01-15,1987-06-24,1987-07-10,2022-05-20
2,BUDD8750038A,30006,Aimargues,54.0,Inondations et/ou Coulées de Boue,1987-02-11,1987-02-13,1987-06-24,1987-07-10,2022-05-20
3,BUDD8750038A,30020,Aubord,54.0,Inondations et/ou Coulées de Boue,1987-02-11,1987-02-13,1987-06-24,1987-07-10,2022-05-20
4,BUDD8750038A,30033,Beauvoisin,54.0,Inondations et/ou Coulées de Boue,1987-02-11,1987-02-13,1987-06-24,1987-07-10,2022-05-20

In [6]:
df["lib_risque_jo"].value_counts()

lib_risque_jo
Inondations et/ou Coulées de Boue                                                                 145433
Sécheresse                                                                                         46365
Mouvement de Terrain                                                                               32298
Tempête                                                                                            16187
Chocs Mécaniques liés à l'action des Vagues                                                         6773
Glissement de Terrain                                                                               3903
Poids de la Neige                                                                                   2758
Mouvements de terrain différentiels consécutifs à la sécheresse et à la réhydratation des sols      1543
Grêle                                                                                               1491
Inondations Remontée Nappe                                                                          1430
Secousse Sismique                                                                                    796
Vents Cycloniques                                                                                    304
Avalanche                                                                                            131
Effondrement et/ou Affaisement                                                                       122
Eboulement et/ou Chute de Blocs                                                                       70
Divers                                                                                                65
Chocs M�caniques li�s � l'action des Vagues                                                           59
Sécheressse                                                                                           55
Mouvements de terrains (hors sécheresse géotechnique)                                                 32
Séismes                                                                                               17
Inondations par choc mécanique des vagues                                                              8
Lave Torrentielle                                                                                      7
Raz de Marée                                                                                           6
Coulée de Boue                                                                                         6
Glissement et Effondrement de Terrain                                                                  5
Glissement et Eboulement Rocheux                                                                       1
Eruption Volcanique                                                                                    1
Choc M�caniques li�s � l'action des Vagues                                                             1
Name: count, dtype: int64

In [3]:
gdf_regions.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 26 entries, 0 to 25
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      26 non-null     str
 1   nom       26 non-null     str
 2   geometry  26 non-null     geometry
dtypes: geometry(1), str(2)
memory usage: 756.0 bytes

In [4]:
gdf_regions.head(10)

,code,nom,geometry
0,01,Guadeloupe,"MULTIPOLYGON (((-61.549 16.2531, -61.5466 16.2..."
1,02,Martinique,"MULTIPOLYGON (((-61.0534 14.4557, -61.0555 14...."
2,03,Guyane,"MULTIPOLYGON (((-52.168 4.7768, -52.1622 4.780..."
3,04,La Réunion,"POLYGON ((55.3223 -21.2529, 55.3206 -21.2491, ..."
4,06,Mayotte,"MULTIPOLYGON (((45.0432 -12.7481, 45.0426 -12...."
5,11,Île-de-France,"POLYGON ((2.52 48.194, 2.523 48.1949, 2.5229 4..."
6,24,Centre-Val de Loire,"POLYGON ((2.5706 46.6592, 2.5696 46.655, 2.567..."
7,27,Bourgogne-Franche-Comté,"POLYGON ((4.622 48.0244, 4.6239 48.0255, 4.634..."
8,28,Normandie,"MULTIPOLYGON (((0.2859 49.4292, 0.2969 49.4299..."
9,32,Hauts-de-France,"POLYGON ((3.9867 49.379, 3.9772 49.3795, 3.972..."

In [11]:
gdf_communes.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 35074 entries, 0 to 35073
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   code         35074 non-null  object
 1   nom          35074 non-null  object
 2   departement  35074 non-null  object
 3   region       35074 non-null  object
 4   commune      45 non-null     object
 5   plm          3 non-null      float64
 6   epci         34931 non-null  object
 7   geometry     35074 non-null  geometry
dtypes: float64(1), geometry(1), object(6)
memory usage: 2.1+ MB

In [12]:
gdf_communes

,code,nom,departement,region,commune,plm,epci,geometry
0,01001,L'Abergement-Clémenciat,01,84,None,NaN,200069193,"POLYGON ((4.9584 46.1533, 4.9516 46.1474, 4.95..."
1,01002,L'Abergement-de-Varey,01,84,None,NaN,240100883,"POLYGON ((5.4302 45.9828, 5.4245 45.9865, 5.42..."
2,01004,Ambérieu-en-Bugey,01,84,None,NaN,240100883,"POLYGON ((5.4088 45.9421, 5.4008 45.9427, 5.39..."
3,01005,Ambérieux-en-Dombes,01,84,None,NaN,200042497,"POLYGON ((4.943 45.9796, 4.9373 45.9789, 4.936..."
4,01006,Ambléon,01,84,None,NaN,200040350,"POLYGON ((5.5708 45.7534, 5.574 45.7539, 5.579..."
...,...,...,...,...,...,...,...,...
35069,98830,Touho,988,988,None,NaN,None,"MULTIPOLYGON (((165.2457 -20.8829, 165.2476 -2..."
35070,98831,Voh,988,988,None,NaN,None,"MULTIPOLYGON (((164.6635 -20.9303, 164.6636 -2..."
35071,98832,Yaté,988,988,None,NaN,None,"MULTIPOLYGON (((167.0287 -22.2694, 167.0322 -2..."
35072,98833,Kouaoua,988,988,None,NaN,None,"MULTIPOLYGON (((165.8247 -21.3904, 165.8242 -2..."
35073,98901,Île de Clipperton,989,989,None,NaN,None,"POLYGON ((-109.2284 10.2975, -109.2306 10.2995..."

In [8]:
df['cod_commune'].head()

0    06120
1    2B050
2    30006
3    30020
4    30033
Name: cod_commune, dtype: str

In [9]:
gdf_communes['code'].head()

0    01001
1    01002
2    01004
3    01005
4    01006
Name: code, dtype: str

In [19]:
gdf_communes[gdf_communes['code']=="30006"]

,code,nom,departement,region,commune,plm,epci,geometry
10916,30006,Aimargues,30,76,None,NaN,243000593,"POLYGON ((4.2152 43.7092, 4.2147 43.7054, 4.21..."

In [12]:
gdf_water.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 142410 entries, 0 to 142409
Data columns (total 11 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   gid         142410 non-null  int64
 1   CdOH        142410 non-null  str
 2   TopoOH      89593 non-null   str
 3   SourceNomO  89542 non-null   str
 4   DateCreati  142410 non-null  str
 5   StatutOH    142410 non-null  str
 6   InfluenceM  1 non-null       float64
 7   CaractereP  2 non-null       float64
 8   Commentair  0 non-null       object
 9   ProjCoordO  142410 non-null  str
 10  geometry    142410 non-null  geometry
dtypes: float64(2), geometry(1), int64(1), object(1), str(6)
memory usage: 12.0+ MB

In [34]:
from src.data.load_data import load_clean_catnat

df_clean = load_clean_catnat()

In [35]:
df_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 247022 entries, 0 to 247021
Data columns (total 7 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   code_commune  247022 non-null  str
 1   lib_commune   247022 non-null  str
 2   num_risque    243805 non-null  float64
 3   type_risque   247022 non-null  str
 4   date_debut    247022 non-null  datetime64[us]
 5   annee         247022 non-null  int64
 6   mois          247022 non-null  int64
dtypes: datetime64[us](1), float64(1), int64(2), str(3)
memory usage: 13.2 MB

In [36]:
df_clean['type_risque'].value_counts()

type_risque
inondation           139280
secheresse            44439
mouvement_terrain     35158
tempete               16329
vagues_submersion      6753
neige_grele            4094
seisme                  780
autre                   189
Name: count, dtype: int64

### GeoDataFrame des catastrophes par communes

In [2]:
from src.data.load_data import load_merged_communes, load_merged_regions

gdf_merged_commune = load_merged_communes()
gdf_merged_regions = load_merged_regions()

In [5]:
gdf_merged_commune.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 246816 entries, 0 to 246815
Data columns (total 8 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   code_commune  246816 non-null  str
 1   lib_commune   246816 non-null  str
 2   num_risque    243599 non-null  float64
 3   type_risque   246816 non-null  str
 4   date_debut    246816 non-null  datetime64[ms]
 5   annee         246816 non-null  int32
 6   mois          246816 non-null  int32
 7   geometry      246816 non-null  geometry
dtypes: datetime64[ms](1), float64(1), geometry(1), int32(2), str(3)
memory usage: 13.2 MB

In [6]:
duplicates = gdf_merged_commune[gdf_merged_commune.duplicated(keep=False)]
len(duplicates)

0

In [7]:
gdf_merged_commune.head()

  code_commune  ...                                           geometry
0        06120  ...  POLYGON ((6.8229 44.2154, 6.8291 44.2199, 6.83...
1        2B050  ...  POLYGON ((8.8154 42.537, 8.8002 42.5281, 8.795...
2        30006  ...  POLYGON ((4.2152 43.7092, 4.2147 43.7054, 4.21...
3        30020  ...  POLYGON ((4.3104 43.7663, 4.3117 43.7687, 4.31...
4        30033  ...  POLYGON ((4.3289 43.7353, 4.334 43.7279, 4.335...

[5 rows x 8 columns]

### GeoDataFrame des catastrophes par region

In [8]:
gdf_merged_regions.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 1610 entries, 0 to 1609
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   region           1610 non-null   str
 1   annee            1610 non-null   int32
 2   type_risque      1610 non-null   str
 3   nb_catastrophes  1610 non-null   int32
 4   code_region      1610 non-null   str
 5   nom_region       1610 non-null   str
 6   geometry         1610 non-null   geometry
dtypes: geometry(1), int32(2), str(4)
memory usage: 75.6 KB

In [9]:
duplicates = gdf_merged_regions[gdf_merged_regions.duplicated(keep=False)]
len(duplicates)

0

In [10]:
gdf_merged_regions.head()

  region  annee  ...  nom_region                                           geometry
0     01   1990  ...  Guadeloupe  MULTIPOLYGON (((-61.549 16.2531, -61.5466 16.2...
1     01   1995  ...  Guadeloupe  MULTIPOLYGON (((-61.549 16.2531, -61.5466 16.2...
2     01   1995  ...  Guadeloupe  MULTIPOLYGON (((-61.549 16.2531, -61.5466 16.2...
3     01   1998  ...  Guadeloupe  MULTIPOLYGON (((-61.549 16.2531, -61.5466 16.2...
4     01   1999  ...  Guadeloupe  MULTIPOLYGON (((-61.549 16.2531, -61.5466 16.2...

[5 rows x 7 columns]

### GeoDataFrame des cours d'eau

In [2]:
from src.data.load_data import load_waterways

gdf_cours_eau = load_waterways()
print(gdf_cours_eau.head())
print(gdf_cours_eau.columns)
print(gdf_cours_eau.crs)

     gid                 CdOH             TopoOH  SourceNomO  \
0  23320  03C0000002000822871       Bras du Vrin  BDCarthage
1  23334  05C0000002000892091                NaN         NaN
2  23338  05C0000002000864205  Bras de l'Argence  BDCarthage
3  23385  05C0000002000890581                NaN         NaN
4  23498  05C0000002215483154  Goute de Picarret         IGN

                DateCreati StatutOH  InfluenceM  CaractereP Commentair  \
0  2017/01/24 16:06:18.918   Validé         NaN         NaN       None
1  2017/01/24 16:06:18.918   Validé         NaN         NaN       None
2  2017/01/24 16:06:18.918   Validé         NaN         NaN       None
3  2017/01/24 16:06:18.918   Validé         NaN         NaN       None
4  2020/10/21 09:35:44.912   Validé         NaN         NaN       None

           ProjCoordO                                           geometry
0  RGF93 / Lambert 93  LINESTRING (718792 6748138.8, 718795.2 6748176...
1  RGF93 / Lambert 93  LINESTRING (486134.2 6296875.9, 486180.2 62968...
2  RGF93 / Lambert 93  LINESTRING (478291 6516351.5, 478303.7 6516337...
3  RGF93 / Lambert 93  LINESTRING (490108.1 6333519.6, 490053.9 63336...
4  RGF93 / Lambert 93  LINESTRING (570644 6205195.5, 570673.8 6205191...
Index(['gid', 'CdOH', 'TopoOH', 'SourceNomO', 'DateCreati', 'StatutOH',
       'InfluenceM', 'CaractereP', 'Commentair', 'ProjCoordO', 'geometry'],
      dtype='str')
EPSG:2154

In [3]:
import importlib
import src.data.merge_data as merge_data

importlib.reload(merge_data)

df_communes_waterways = merge_data.merge_communes_cours_eau()
df_communes_waterways.head()

,code_commune,nom_commune,liste_cours_eau,liste_geometries_cours_eau,nb_cours_eau
0,01001,L'Abergement-Clémenciat,"['Bief Bourbon', 'Bief de Payon', 'Bief de Ver...","['LINESTRING (4.933622 46.166878, 4.933353 46....",4
1,01002,L'Abergement-de-Varey,"[""l'Oiselon"", 'le Riez']","['LINESTRING (5.460599 45.979931, 5.460631 45....",2
2,01004,Ambérieu-en-Bugey,"[""l'Albarine"", 'le Champelin', 'le Foulon', 'l...","['LINESTRING (5.373634 45.967115, 5.373422 45....",4
3,01005,Ambérieux-en-Dombes,['le Formans'],"['LINESTRING (4.887605 45.989378, 4.887555 45....",1
4,01006,Ambléon,['le Setrin'],"['LINESTRING (5.597188 45.748443, 5.597578 45....",1