In [1]:
%pip install geopandas

Requirement already satisfied: geopandas in c:\users\narji\appdata\local\programs\python\python311\lib\site-packages (1.1.2)
Requirement already satisfied: numpy>=1.24 in c:\users\narji\appdata\roaming\python\python311\site-packages (from geopandas) (1.26.4)
Requirement already satisfied: pyogrio>=0.7.2 in c:\users\narji\appdata\local\programs\python\python311\lib\site-packages (from geopandas) (0.12.1)
Requirement already satisfied: packaging in c:\users\narji\appdata\roaming\python\python311\site-packages (from geopandas) (24.2)
Requirement already satisfied: pandas>=2.0.0 in c:\users\narji\appdata\local\programs\python\python311\lib\site-packages (from geopandas) (2.2.3)
Requirement already satisfied: pyproj>=3.5.0 in c:\users\narji\appdata\local\programs\python\python311\lib\site-packages (from geopandas) (3.7.2)
Requirement already satisfied: shapely>=2.0.0 in c:\users\narji\appdata\local\programs\python\python311\lib\site-packages (from geopandas) (2.1.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\narji\appdata\roaming\python\python311\site-packages (from pandas>=2.0.0->geopandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\narji\appdata\local\programs\python\python311\lib\site-packages (from pandas>=2.0.0->geopandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\narji\appdata\local\programs\python\python311\lib\site-packages (from pandas>=2.0.0->geopandas) (2025.1)
Requirement already satisfied: certifi in c:\users\narji\appdata\local\programs\python\python311\lib\site-packages (from pyogrio>=0.7.2->geopandas) (2024.12.14)
Requirement already satisfied: six>=1.5 in c:\users\narji\appdata\roaming\python\python311\site-packages (from python-dateutil>=2.8.2->pandas>=2.0.0->geopandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
import geopandas as gpd

file_path = r"C:\Users\Narji\Downloads\CoursEau_FXX-shp-20260227T123048Z-1-001\CoursEau_FXX-shp\CoursEau_FXX.shp"
gdf = gpd.read_file(file_path)

In [6]:
gdf.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 142410 entries, 0 to 142409
Data columns (total 11 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   gid         142410 non-null  int64
 1   CdOH        142410 non-null  object
 2   TopoOH      89593 non-null   object
 3   SourceNomO  89542 non-null   object
 4   DateCreati  142410 non-null  object
 5   StatutOH    142410 non-null  object
 6   InfluenceM  1 non-null       float64
 7   CaractereP  2 non-null       float64
 8   Commentair  0 non-null       object
 9   ProjCoordO  142410 non-null  object
 10  geometry    142410 non-null  geometry
dtypes: float64(2), geometry(1), int64(1), object(7)
memory usage: 12.0+ MB

In [7]:
gdf.head()

,gid,CdOH,TopoOH,SourceNomO,DateCreati,StatutOH,InfluenceM,CaractereP,Commentair,ProjCoordO,geometry
0,23320,03C0000002000822871,Bras du Vrin,BDCarthage,2017/01/24 16:06:18.918,Validé,NaN,NaN,None,RGF93 / Lambert 93,"LINESTRING (718792 6748138.8, 718795.2 6748176..."
1,23334,05C0000002000892091,None,None,2017/01/24 16:06:18.918,Validé,NaN,NaN,None,RGF93 / Lambert 93,"LINESTRING (486134.2 6296875.9, 486180.2 62968..."
2,23338,05C0000002000864205,Bras de l'Argence,BDCarthage,2017/01/24 16:06:18.918,Validé,NaN,NaN,None,RGF93 / Lambert 93,"LINESTRING (478291 6516351.5, 478303.7 6516337..."
3,23385,05C0000002000890581,None,None,2017/01/24 16:06:18.918,Validé,NaN,NaN,None,RGF93 / Lambert 93,"LINESTRING (490108.1 6333519.6, 490053.9 63336..."
4,23498,05C0000002215483154,Goute de Picarret,IGN,2020/10/21 09:35:44.912,Validé,NaN,NaN,None,RGF93 / Lambert 93,"LINESTRING (570644 6205195.5, 570673.8 6205191..."

In [8]:
gdf.columns

Index(['gid', 'CdOH', 'TopoOH', 'SourceNomO', 'DateCreati', 'StatutOH',
       'InfluenceM', 'CaractereP', 'Commentair', 'ProjCoordO', 'geometry'],
      dtype='object')

In [11]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Narji\Downloads\gaspar\catnat_gaspar.csv", sep=";")

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 259867 entries, 0 to 259866
Data columns (total 10 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   cod_nat_catnat  259867 non-null  object
 1   cod_commune     259867 non-null  object
 2   lib_commune     259867 non-null  object
 3   num_risque_jo   256647 non-null  float64
 4   lib_risque_jo   259867 non-null  object
 5   dat_deb         259867 non-null  object
 6   dat_fin         259867 non-null  object
 7   dat_pub_arrete  259867 non-null  object
 8   dat_pub_jo      259867 non-null  object
 9   dat_maj         259867 non-null  object
dtypes: float64(1), object(9)
memory usage: 19.8+ MB

In [13]:
df.head()

,cod_nat_catnat,cod_commune,lib_commune,num_risque_jo,lib_risque_jo,dat_deb,dat_fin,dat_pub_arrete,dat_pub_jo,dat_maj
0,BUDD8750027A,06120,Saint-Étienne-de-Tinée,63.0,Glissement de Terrain,1985-01-01,1986-12-31,1987-05-20,1987-05-24,2022-05-20
1,BUDD8750038A,2B050,Calvi,54.0,Inondations et/ou Coulées de Boue,1987-01-14,1987-01-15,1987-06-24,1987-07-10,2022-05-20
2,BUDD8750038A,30006,Aimargues,54.0,Inondations et/ou Coulées de Boue,1987-02-11,1987-02-13,1987-06-24,1987-07-10,2022-05-20
3,BUDD8750038A,30020,Aubord,54.0,Inondations et/ou Coulées de Boue,1987-02-11,1987-02-13,1987-06-24,1987-07-10,2022-05-20
4,BUDD8750038A,30033,Beauvoisin,54.0,Inondations et/ou Coulées de Boue,1987-02-11,1987-02-13,1987-06-24,1987-07-10,2022-05-20